DROP DATABASE IF EXISTS webschool;
CREATE DATABASE webschool DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE webschool;

CREATE TABLE permission (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,

  CONSTRAINT id PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fio VARCHAR(45) NULL,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT fio UNIQUE KEY (fio)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE user_permission (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED,
  permission_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT user_id_permission FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT permission_id FOREIGN KEY (permission_id) REFERENCES permission(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE course (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  teacher_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT teacher_id FOREIGN KEY (teacher_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE course_user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED,
  course_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT user_id_course FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT course_id_user FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE topic (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  text VARCHAR(2000) NULL,
  course_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT course_id_topic FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE task (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  text VARCHAR(300) NULL,
  solution VARCHAR(200) NULL,
  topic_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT topic_id_task FOREIGN KEY (topic_id) REFERENCES topic(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE question (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  text VARCHAR(200) NULL,
  topic_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT topic_id_question FOREIGN KEY (topic_id) REFERENCES topic(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE answer (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  text VARCHAR(100) NULL,
  isRight BOOLEAN,
  question_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT question_id FOREIGN KEY (question_id) REFERENCES question(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE journal (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mark INT UNSIGNED NULL,
  topic_id INT UNSIGNED,
  student_id INT UNSIGNED,

  CONSTRAINT id PRIMARY KEY (id),
  CONSTRAINT topic_id_journal FOREIGN KEY (topic_id) REFERENCES topic(id) ON DELETE CASCADE,
  CONSTRAINT student_id FOREIGN KEY (student_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;
